import type { NewProject, NewProjectPoint } from './schema'

/**
 * Fixture data for dev mode and tests. NOT real data: coordinates are
 * approximate, costs are invented and source_doc/source_page are placeholders.
 * Shaped to cover the cases the routes have to handle:
 *   - DESC:6808 N,O  an id containing a comma, and a null start_date
 *   - GPC:20793      an in-scope DESC x GPC pair under 25 mi, sharing "Thurmond"
 *   - GPC:19523      unlocated (lat/lon null, confidence pinned to the 'low' floor)
 *   - GPC:21044      owner GTC, so it only appears when inScope=false
 */
export const FIXTURE_PROJECTS: NewProject[] = [
  {
    utility: 'DESC',
    projectKey: '6810 A',
    name: 'Hooks - Thurmond 115kV Tie: Rebuild',
    description: 'Fixture data. Rebuild the Hooks - Thurmond 115kV tie line.',
    owner: 'DESC',
    projectType: 'line',
    workType: 'rebuild',
    voltageKv: 115,
    zone: null,
    status: 'Planned',
    startDate: '2021-12-31',
    startDateSource: 'estimated',
    inServiceDate: '2024-12-31',
    inServiceRaw: '12/31/2024',
    lineMiles: 2.1,
    milesSource: 'stated',
    costUsd: 2200080,
    costLow: 2200080,
    costHigh: 2200080,
    sourceDoc: 'fixture.pdf',
    sourcePage: 3,
  },
  {
    utility: 'DESC',
    projectKey: '6808 N,O',
    name: 'Stevens Creek - Hooks 115kV Rebuild',
    description: 'Fixture data. Project key contains a comma on purpose.',
    owner: 'DESC',
    projectType: 'line',
    workType: 'rebuild',
    voltageKv: 115,
    zone: null,
    status: 'In Progress',
    startDate: null,
    startDateSource: null,
    inServiceDate: '2026-06-30',
    inServiceRaw: '6/30/2026',
    lineMiles: 7.4,
    milesSource: 'stated',
    costUsd: 8100000,
    costLow: 8100000,
    costHigh: 8100000,
    sourceDoc: 'fixture.pdf',
    sourcePage: 4,
  },
  {
    utility: 'GPC',
    projectKey: '20793',
    name: 'EVANS PRIMARY - THURMOND DAM (USA) #5 115KV REBUILD',
    description: 'Fixture data. Rebuild toward Thurmond Dam.',
    owner: 'GPC',
    projectType: 'line',
    workType: 'rebuild',
    voltageKv: 115,
    zone: 'Zone 3',
    status: null,
    startDate: '2030-06-01',
    startDateSource: 'published',
    inServiceDate: '2033-06-01',
    inServiceRaw: '6/1/2033',
    lineMiles: 9.2,
    milesSource: 'stated',
    costUsd: 9600000,
    costLow: 7700000,
    costHigh: 11500000,
    sourceDoc: 'fixture.pdf',
    sourcePage: 17,
  },
  {
    utility: 'GPC',
    projectKey: '19523',
    name: 'SAV: CC - HYUNDAI MOTORS SAVANNAH',
    description: 'Fixture data. Unlocated: no point has coordinates yet.',
    owner: 'SAV',
    projectType: 'multi_station',
    workType: 'new_build',
    voltageKv: 230,
    zone: 'Zone 7',
    status: null,
    startDate: '2026-01-01',
    startDateSource: 'from_spend_year',
    inServiceDate: '2028-12-31',
    inServiceRaw: '12/31/2028',
    lineMiles: null,
    milesSource: 'not_applicable',
    costUsd: null,
    costLow: null,
    costHigh: null,
    sourceDoc: 'fixture.pdf',
    sourcePage: 22,
  },
  {
    utility: 'GPC',
    projectKey: '21044',
    name: 'GTC TIE STATION UPGRADE',
    description: 'Fixture data. Owner GTC, so it is out of the default scope.',
    owner: 'GTC',
    projectType: 'station',
    workType: 'station_equipment',
    voltageKv: 230,
    zone: 'Zone 3',
    status: null,
    startDate: '2029-03-31',
    startDateSource: 'published',
    inServiceDate: '2031-03-31',
    inServiceRaw: '3/31/2031',
    lineMiles: null,
    milesSource: 'not_applicable',
    costUsd: 1400000,
    costLow: 1100000,
    costHigh: 1700000,
    sourceDoc: 'fixture.pdf',
    sourcePage: 31,
  },
]

export const FIXTURE_POINTS: NewProjectPoint[] = [
  {
    projectId: 'DESC:6810 A',
    seq: 1,
    name: 'Hooks',
    lat: 33.64,
    lon: -82.16,
    method: 'osm',
    matchName: 'Hooks Substation',
    osmUrl: 'https://www.openstreetmap.org/node/1000001',
    matchScore: 90,
    confidence: 'medium',
  },
  {
    projectId: 'DESC:6810 A',
    seq: 2,
    name: 'Thurmond',
    lat: 33.66,
    lon: -82.19,
    method: 'osm',
    matchName: 'Thurmond Substation',
    osmUrl: 'https://www.openstreetmap.org/node/1000002',
    matchScore: 88,
    confidence: 'medium',
  },
  {
    projectId: 'DESC:6808 N,O',
    seq: 1,
    name: 'Stevens Creek',
    lat: 33.562599,
    lon: -82.051362,
    method: 'osm',
    matchName: 'Stevens Creek Substation',
    osmUrl: 'https://www.openstreetmap.org/node/1000003',
    matchScore: 95,
    confidence: 'high',
  },
  {
    projectId: 'DESC:6808 N,O',
    seq: 2,
    name: 'Hooks',
    lat: 33.64,
    lon: -82.16,
    method: 'osm',
    matchName: 'Hooks Substation',
    osmUrl: 'https://www.openstreetmap.org/node/1000001',
    matchScore: 95,
    confidence: 'high',
  },
  {
    projectId: 'GPC:20793',
    seq: 1,
    name: 'Evans Primary',
    lat: 33.534,
    lon: -82.13,
    method: 'nominatim',
    matchName: 'Evans Primary Substation',
    osmUrl: 'https://www.openstreetmap.org/node/1000004',
    matchScore: 72,
    confidence: 'medium',
  },
  {
    projectId: 'GPC:20793',
    seq: 2,
    name: 'Thurmond Dam',
    lat: 33.663,
    lon: -82.195,
    method: 'nominatim',
    matchName: 'J. Strom Thurmond Dam',
    osmUrl: 'https://www.openstreetmap.org/node/1000005',
    matchScore: 68,
    confidence: 'medium',
  },
  {
    projectId: 'GPC:19523',
    seq: 1,
    name: 'Hyundai Motors Savannah',
    lat: null,
    lon: null,
    method: null,
    matchName: null,
    osmUrl: null,
    matchScore: null,
    confidence: 'low',
  },
  {
    projectId: 'GPC:19523',
    seq: 2,
    name: 'Newton Rd',
    lat: null,
    lon: null,
    method: null,
    matchName: null,
    osmUrl: null,
    matchScore: null,
    confidence: 'low',
  },
  {
    projectId: 'GPC:21044',
    seq: 1,
    name: 'GTC Tie',
    lat: 33.645,
    lon: -82.17,
    method: 'osm',
    matchName: 'GTC Tie Station',
    osmUrl: 'https://www.openstreetmap.org/node/1000006',
    matchScore: 60,
    confidence: 'low',
  },
]
